### ISSUE TITLE
move repo to Github organization

### ISSUE THREAD

**Issue by markstos** [node-strava/node-strava-v3#122]
This project is now community-maintained. The original author, @UnbounDev is not involved much. 

I'm the primary maintainer, but really I'm just another user who happens to have commit and publish rights. Maintenance is being down by a community of users like @edilson so improved a few things in the most recent release. 

With the blessing of @UnbounDev I'd like to create a new Github organization, like `node-strava` and move the project into that neutral namespace, as a step towards possibly expanding the number of users with commit and release rights. @UnbounDev is welcome to maintain commit access there. 

I helped the `passport-saml` project go through a similar transition and it worked quite well. That project is now more active then it ever has been. It's the #1 SAML library for Node and has made rapid improvements lately with better TypeScript support among other features and bug fixes.

Although Strava has their own Swagger-based client, clearly there is ongoing demand for a Node Strava client that is installable from NPM and works in a more conventional way.

**Comment by UnbounDev** [comment]
Thank you for making this proposal and maintaining this project, @markstos, I am very grateful to you and the community for extending the project's life.

Please create a neutral space, as you see fit, and move the repository into that space. Please let me know if I can assist in any way.

**Comment by markstos** [comment]
@UnbounDev I have created a "node-strava" organization and invited you as an owner. The next steps are for you to accept the invitation and initiate the transfer there: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository Once that's done, you can choose how much want to be involved in the new organization going forward.  I also invited @edilson as a recent contributor to join as an organization owner as well.

**Comment by UnbounDev** [comment]
Alright, this repo has a shiny new home: https://github.com/node-strava/node-strava-v3

Thanks again to you, @markstos and @edilson and all the rest of the community!

**Comment by markstos** [comment]
Thanks @UnbounDev! As part of this transition, I made a couple of other changes:

 - Renamed `master` branch to `main`. Local checkouts will not be automatically updated.
 - Enabled a branch-protection rule for `main` so for now that a pull request and peer-review is required. My hope is that @edilson will continue to help with maintenance either by submitting PRs or reviewing them. If we end up with a single active maintainer again, we'll have to re-evaluate the mandatory peer-review rule. It may also be useful to set up Slack for private maintainer conversations, but we can consider that another time.
