### ISSUE TITLE
Create a project to map features

### ISSUE THREAD

**Issue by edilson** [node-strava/node-strava-v3#123]
I think it would be nice if we could map the features that weren't implemented yet, for that we could create a board and list what has to be done, what is in progress and what is already done.

**Comment by markstos** [comment]
@edilson You are now an admin of the new `node-strava` project and are welcome to work on something like this.

**Comment by edilson** [comment]
@markstos i was just consulting the Strava documentation and i believe that there is some features on our wrap that we can remove, its those

```JS
activities.prototype.listFriends = function (args, done) {
  var endpoint = 'activities/following/'
  return this._listHelper(endpoint, args, done)
}
```

```JS
activities.prototype.listPhotos = function (args, done) {
  _requireActivityId(args)

  var endpoint = 'activities/' + args.id + '/photos'

  var pageQS = this.client.getPaginationQS(args)

  var completeQS = pageQS

  // should be true according to Strava API docs
  args.photo_sources = true
  var argsQS = this.client.getQS(['size', 'photo_sources'], args)

  if (completeQS && completeQS.length) {
    completeQS += '&'
  }
  completeQS += argsQS

  endpoint += '?' + completeQS

  return this.client.getEndpoint(endpoint, args, done)
}
```

could you confirm that? I saw this doc:

```
https://developers.strava.com/docs/reference/
https://developers.strava.com/playground/
```

**Comment by markstos** [comment]
@edilson I agree-- those "friend" routes don't appear documented anymore. Strava has generally gotten more privacy-centric over time

**Comment by markstos** [comment]
Closing this feature request due to lack of interest, but anyone wants to pick it up and improve the docs for this module, fee free.
