### ISSUE TITLE
Can not import strava with Typescript

### ISSUE THREAD

**Issue by nqdai1992** [node-strava/node-strava-v3#129]
I think there is a problem with Typescript declaration file

The way that I import the lib
`import { default as strava } from 'strava-v3';`
When I call API
`const activities = await strava.activities.get({ });`
The error that I received
`TypeError: Cannot read properties of undefined (reading 'activities')`

**Comment by markstos** [comment]
Patch welcome.

**Comment by edilson** [comment]
@nqdai1992 haver you tried without destructuring it? I think that if you want to destructure it's possible to get the activities directly

**Comment by mikehhhhhhh** [comment]
I also ran into this issue. As a long term js dev and a new ts dev, the best solution I could find was to switch both js and ts to a named export.

According to the docs, the previous solution should work so I'm not sure why it does not.

**Comment by markstos** [comment]
Closing as dupe of #144
