### ISSUE TITLE
Allow property SportType in strava.activities.update 

### ISSUE THREAD

**Issue by pro-sumer** [node-strava/node-strava-v3#130]
Strava introduced a new property [SportType](https://developers.strava.com/docs/reference/#api-models-SportType):

> SportType: An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)

Can you please add this to the allowed properties for `strava.activities.update`?

I think you only need to add it to the `_updateAllowedProps` array in `activities.js` to support this?

(use case: bulk changing my "rides" to MTB rides)

**Comment by markstos** [comment]
PR welcome. In the PR submission, please provide notes about how the change was tested.

**Comment by markstos** [comment]
This is a community-maintained module now. The original author is no longer active. I'm another user like you who happens to have commit access. I don't need this feature now but am willing to review and release it.

**Comment by pro-sumer** [comment]
PR #132 submitted to solve this issue.
